version: '3.8'

services:
  frontend:
    build:
      context: .  # Define o contexto como o diretório atual (frontend)
      dockerfile: Dockerfile  # Indica qual Dockerfile usar
    ports:
      - "3000:80"  # Mapeia a porta 80 do container (nginx) para a porta 3000 do host
  #   depends_on:
  #     - backend  # Garante que o backend esteja disponível antes de iniciar o frontend

  # backend:
  #   external: true  # Indica que o serviço backend está em outro docker-compose
