version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URI: postgres://user:password@db:5432/yourdbname
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # Ajuste para o diretório do seu frontend
    ports:
      - "3000:3000"  # Ajuste para a porta do seu frontend
    depends_on:
      - backend

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
